Repository PICKTRE/PICKTRE_frontend, pull requests merged in 2023-09, with the labels that each got.

#2 Feat/issue 1
  .eslintrc.cjs
  .gitignore
  index.html
  package-lock.json
  package.json
  public/vite.svg
  src/App.css
  src/App.jsx
  src/assets/react.svg
  src/index.css
  src/main.jsx
  vite.config.js
Labels: Establish

#4 feat/issue-3
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/assets/camera.png
  src/assets/map.png
  src/assets/myPageLogo.png
  src/assets/mypage.png
  src/assets/point.png
  src/assets/react.svg
  src/assets/setting.png
  src/components/common/Footer.jsx
  src/components/common/Footer.module.css
  src/components/common/Header.jsx
  src/components/common/Header.module.css
  src/components/common/HeaderLayout.jsx
  src/components/common/HeaderLayout.module.css
  src/index.css
  src/main.jsx
Labels: Feat

#8 Feat/issue 7
  src/App.jsx
  src/components/landingPage/LandingPage.jsx
  src/components/landingPage/LandingPage.module.css
  src/components/landingPage/Logo.jsx
  src/components/landingPage/Logo.module.css
  src/components/landingPage/RedirectPage.jsx
  src/components/landingPage/SocialAccountButton.jsx
  src/components/landingPage/SocialAccountButton.module.css
Labels: Feat

#10 feat/issue-9
  src/App.jsx
  src/components/myPage/MyPage.jsx
  src/components/setting/Setting.jsx
  src/components/setting/Setting.module.css
Labels: Feat

#14 feat/issue-11
  src/App.jsx
  src/components/benefit/Benefit.jsx
  src/components/benefit/Benefit.module.css
  src/components/benefit/BenefitSection.jsx
  src/components/benefit/BenefitSection.module.css
  src/components/benefit/GradeSection.jsx
  src/components/benefit/GradeSection.module.css
Labels: Feat

#15 feat/issue-12
  package-lock.json
  package.json
  src/App.jsx
  src/components/camera/QRcamera.jsx
  src/components/camera/QRcamera.module.css
  src/components/common/Footer.jsx
  src/components/common/Header.jsx
Labels: Feat

#17 feat/issue-16
  src/App.jsx
  src/components/inviteFriends/InviteFriends.jsx
  src/components/inviteFriends/InviteFriends.module.css
  src/components/inviteFriends/InviteFriendsButton.jsx
  src/components/inviteFriends/InviteFriendsButton.module.css
Labels: Feat

#21 Feat/issue-18
  package-lock.json
  package.json
  src/App.jsx
  src/components/myUseReport/ActivityGraph.jsx
  src/components/myUseReport/BadgeTitle.jsx
  src/components/myUseReport/MyUseReport.jsx
  src/components/myUseReport/MyUseReport.module.css
  src/components/myUseReport/activityGraph.module.css
  src/components/myUseReport/badgeTitle.module.css
Labels: Feat

#23 [Feat]: Home 페이지 구현
  src/App.jsx
  src/components/home/Home.jsx
  src/components/home/Home.module.css
  src/components/home/HomeButton.jsx
  src/components/home/HomeButton.module.css
  src/components/home/HomeCard.jsx
  src/components/home/HomeCard.module.css
  src/components/home/HomeLevel.jsx
  src/components/home/HomeLevel.module.css
  src/components/home/HomeMainPostText.jsx
  src/components/home/HomeMainPostText.module.css
  src/components/home/HomeReward.jsx
  src/components/home/HomeReward.module.css
  src/components/home/dummy/cardData.json
Labels: Feat

#26 feat/issue-25
  package-lock.json
  package.json
  src/App.jsx
  src/components/map/GeoLocation.jsx
  src/components/map/Map.jsx
  src/components/map/Map.module.css
  src/constants/OAuth.jsx
Labels: Feat

#28 feat/issue-20
  src/App.jsx
  src/components/common/HeaderLayout.module.css
  src/components/point/Point.jsx
  src/components/point/Point.module.css
  src/components/point/PointDropdown.jsx
  src/components/point/PointDropdown.module.css
  src/components/point/PointList.jsx
  src/components/point/PointList.module.css
  src/components/point/PointListElement.jsx
  src/components/point/PointListElement.module.css
  src/components/point/PointProfile.jsx
  src/components/point/PointProfile.module.css
  src/components/point/dummy/pointData.json
  src/components/point/dummy/profileData.json
Labels: Feat

#33 feat/issue-29
  src/App.jsx
  src/components/ranking/Ranker.jsx
  src/components/ranking/Ranker.module.css
  src/components/ranking/Ranking.jsx
  src/components/ranking/Ranking.module.css
  src/components/ranking/RankingList.jsx
Labels: Feat

#34 feat/issue-30
  package-lock.json
  package.json
  src/App.jsx
  src/components/store/Store.jsx
  src/components/store/Store.module.css
  src/components/store/StoreDividingLine.jsx
  src/components/store/StoreDividingLine.module.css
  src/components/store/StoreGoods.jsx
  src/components/store/StoreGoods.module.css
  src/components/store/StoreOther.jsx
  src/components/store/StoreOther.module.css
  src/components/store/StorePopular.jsx
  src/components/store/StorePopular.module.css
  src/components/store/StoreSearching.jsx
  src/components/store/StoreSearching.module.css
  src/components/store/modal/StoreGoodsModal.jsx
  src/components/store/modal/StoreGoodsModal.module.css
Labels: Feat

#35 feat/issue-31
  package-lock.json
  package.json
  src/App.jsx
  src/components/common/AccordionList.jsx
  src/components/common/AccordionList.module.css
  src/components/common/chevron-down.svg
  src/components/notice/Notice.jsx
  src/components/notice/Notice.module.css
  src/components/notice/dummy/noticeData.json
Labels: Feat

#36 feat/issue-32
  src/App.jsx
  src/components/qna/Qna.jsx
  src/components/qna/Qna.module.css
  src/components/qna/dummy/qnaData.json
Labels: Feat

#39 Fix/issue 38
  index.html
  public/PICTRE.ico
  public/_redirects
  src/App.jsx
Labels: 👹 BugFix, ✨ Feature, 🌏 Deploy, 🎨 Styling

#41 docs/issue-37
  README.md
  readmeImg/QR_코드_리더기_페이지.png
  readmeImg/공지사항.png
  readmeImg/등급별_혜택안내.png
  readmeImg/랭킹.png
  readmeImg/마이페이지.png
  readmeImg/메인홈페이지.png
  readmeImg/설정.png
  readmeImg/스토어.png
  readmeImg/쓰레기_인식_카메라_페이지.png
  readmeImg/이용리포트.png
  readmeImg/자주_묻는_질문.png
  readmeImg/지도.png
  readmeImg/친구_초대하기.png
  readmeImg/포인트.png
Labels: 📃 Docs, 🎨 Styling

#44 refactor/issue-40
  src/components/benefit/Benefit.jsx
  src/components/benefit/BenefitSection.jsx
  src/components/benefit/GradeSection.jsx
  src/components/camera/QRcamera.jsx
  src/components/camera/TrashCameraEwaste.jsx
  src/components/camera/TrashCameraGlass.jsx
  src/components/camera/TrashCameraMedical.jsx
  src/components/camera/TrashCameraMetal.jsx
  src/components/camera/TrashCameraPaper.jsx
  src/components/camera/TrashCameraPlastic.jsx
  src/components/home/Home.jsx
  src/components/home/HomeButton.jsx
  src/components/home/HomeCard.jsx
  src/components/home/HomeLevel.jsx
  src/components/home/HomeMainPostText.jsx
  src/components/home/HomeReward.jsx
  src/components/inviteFriends/InviteFriends.jsx
  src/components/inviteFriends/InviteFriendsButton.jsx
  src/components/map/GeoLocation.jsx
  src/components/map/Map.jsx
  src/components/myPage/MyList.jsx
  src/components/myPage/MyPage.jsx
  src/components/myPage/MyProfile.jsx
  src/components/myPage/MySubPost.jsx
  src/components/myUseReport/ActivityGraph.jsx
  src/components/myUseReport/BadgeTitle.jsx
  src/components/myUseReport/MyUseReport.jsx
  src/components/notice/Notice.jsx
  src/components/point/Point.jsx
  src/components/point/PointDropdown.jsx
  src/components/point/PointList.jsx
  src/components/point/PointListElement.jsx
  src/components/point/PointProfile.jsx
  src/components/qna/Qna.jsx
  src/components/ranking/Ranker.jsx
  src/components/ranking/Ranking.jsx
  src/components/ranking/RankingList.jsx
  src/components/setting/Setting.jsx
  src/components/store/Store.jsx
  src/components/store/StoreDividingLine.jsx
  src/components/store/StoreGoods.jsx
  src/components/store/StoreOther.jsx
  src/components/store/StorePopular.jsx
  src/components/store/StoreSearching.jsx
Labels: 🔨 Refactor

#48 Docs/issue 47
  README.md
  README_Img/QR_ewaste.png
  README_Img/QR_glass.png
  README_Img/QR_medical.png
  README_Img/QR_metal.png
  README_Img/QR_paper.png
  README_Img/QR_plastic.png
Labels: 📃 Docs, 🎨 Styling

#50 BugFix/issue-49
  src/components/myPage/MyList.jsx
  src/components/store/StoreGoods.jsx
Labels: 👹 BugFix
